### PR TITLE
chore: use new pre-released data plane SDK

### PR DESCRIPTION
**Pull request by wikimonkey**
**Issue #, if available:**

**Description of changes:**
Use new pre-release data plane SDK which contains two existing component service APIs and three new client device APIs

**Why is this change necessary:**
client device management components need to integrate with greengrass cloud

**How was this change tested:**
existing tests pass

**Any additional information or context required to review the change:**

**Checklist:**
 - [ ] Updated the README if applicable
 - [ ] Updated or added new unit tests
 - [ ] Updated or added new integration tests
 - [ ] Updated or added new end-to-end tests
 - [ ] If your code makes a remote network call, it was tested with a proxy

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by MikeDombo — COMMENTED** [review]
Why are there so many changes? This change should only be commenting out the old SDK and bringing in the new SDK in the POM.

**Comment by wikimonkey** [comment]
> Why are there so many changes? This change should only be commenting out the old SDK and bringing in the new SDK in the POM.

the class name and namespace got changed to distinguish from control plane SDK, otherwise it could have name conflicts.

**Comment by MikeDombo** [comment]
> > Why are there so many changes? This change should only be commenting out the old SDK and bringing in the new SDK in the POM.
> 
> the class name and namespace got changed to distinguish from control plane SDK, otherwise it could have name conflicts.

Why is there a difference? The SDK(s) are the same, they just use different HTTP clients. This renaming is absolutely not necessary. The existing "component service" client _is_ the data plane client. The control plane client is basically not used; it is only used a bit during provisioning.

**Comment by wikimonkey** [comment]
> > > Why are there so many changes? This change should only be commenting out the old SDK and bringing in the new SDK in the POM.
> > 
> > 
> > the class name and namespace got changed to distinguish from control plane SDK, otherwise it could have name conflicts.
> 
> Why is there a difference? The SDK(s) are the same, they just use different HTTP clients. This renaming is absolutely not necessary. The existing "component service" client _is_ the data plane client. The control plane client is basically not used; it is only used a bit during provisioning.

Existing SDK is still used for some places (e.g. testing), so the new data plane SDK is using a slightly different namespace to avoid conflicts I believe.

The reason I rename `GreengrassComponentServiceClientFactory` to `GreengrassServiceClientFactory` is obvious: in GGAD or the other places (e.g. large configuration) we can use this client factory, so it shouldn't be called `component` service I think.

**Review by MikeDombo — CHANGES_REQUESTED** [review]
Do not create new namespaces for the client.

**Comment by wikimonkey** [comment]
> Do not create new namespaces for the client.

Discussed offline with SDK provider, the initiative is to separate control and data plane SDK. SDK team requires new data plane SDK to use different namespace. So if we would like to separate SDK, we can't use the same namespace.

**Review by jbutler — APPROVED** [review]

**Review by k-khatri — APPROVED** [review]

**Review by MikeDombo — APPROVED** [review]

**Pull request merged**
