### PR TITLE
docs: fix grammar in readme

### PR DESCRIPTION
**Pull request by tarehart**
**Description of changes:** Removing an errant apostrophe. This should be the possessive "its", not the contraction "it's."

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by MikeDombo** [comment]
Thank you for the contribution. To accept this you will need to amend your commit message to follow conventionalcommits format, such as `docs: fix grammar`.

**Comment by tarehart** [comment]
Ok! Force-pushed a revised commit message.

**Review by MikeDombo — APPROVED** [review]

**Review by shaguptashaikh — APPROVED** [review]

**Comment by MikeDombo** [comment]
Thank you for the fix and congrats on being PR #1400.

**Comment by tarehart** [comment]
Thanks for the super quick response!

**Pull request merged**
